"""
Django settings for pro1 project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))     #获取项目根目录


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1#kl3$x)!)pa(flz6x8b-3_v&&)qsd)a3d(or7$_==*64uwp%)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_1',
    'student',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',    #Csrf验证 用于在get获取数据时在浏览器端写入验证信息，并在post提交数据时检测该信息
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pro1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],      #声明存放查找html文件的目录 .../templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pro1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',    # 默认
        'NAME': 'school',                        # 连接的数据库
        'HOST': '127.0.0.1',                     # mysql的ip地址
        'PORT': 3306,                            # mysql的端口
        'USER': 'root',                          # mysql的用户名
        'PASSWORD': 'root',                      # mysql的密码
    }
}
'''
DATABASES = {
    #sqlist配置
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  #en-us为英文  zh-hans 为中文

TIME_ZONE = 'Asia/shanghai'  #UTC为标准时间  Asia/shanghai为中国时间

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'       #定义访问静态文件的URL前缀
STATICFILES_DIRS=[os.path.join(BASE_DIR, 'static'), ]    ##声明存放查找静态文件的目录 .../static


#Session配置
#SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # 引擎   将session存入缓存中
#SESSION_CACHE_ALIAS = 'default'                            # 使用的缓存别名（默认内存缓存，也可以是memcache），此处别名依赖缓存的设置

#SESSION_ENGINE = 'django.contrib.sessions.backends.db'   # 引擎（默认）将session存入数据库中
SESSION_COOKIE_NAME = "sessionid"                         # Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串（默认）
#SESSION_COOKIE_PATH = "/"                                # Session的cookie保存的路径（默认）
#SESSION_COOKIE_DOMAIN = None                             # Session的cookie保存的域名（默认）
#SESSION_COOKIE_SECURE = False                            # 是否Https传输cookie（默认）
#SESSION_COOKIE_HTTPONLY = True                           # 是否Session的cookie只支持http传输（默认）
SESSION_COOKIE_AGE = 1209600                               # Session的cookie失效日期（2周）（默认）
#SESSION_EXPIRE_AT_BROWSER_CLOSE = False                  # 是否关闭浏览器使得Session过期（默认）
SESSION_SAVE_EVERY_REQUEST = True                         # 是否每次请求都保存Session，默认修改之后才保存（默认False 及到时间失效 True为有操作时一直不失效）
